name: "Pangolin-CLI"
version: 0.17.0.c
slug: "pangolin-cli"
description: "Pangolin-CLI client for Home Assistant, for Pangolin connectivity"
icon: "icon.png"
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
startup: services
boot: auto
host_network: true
full_access: true
apparmor: false
privileged:
  - NET_ADMIN
  - NET_RAW
options:
  PANGOLIN_ENDPOINT: "https://pangolin.example.com"
  SITE_ID: "your_site_id"
  SITE_SECRET: "your_site_secret"
  custom_env_vars: []
schema:
  PANGOLIN_ENDPOINT: "str"
  SITE_ID: "str"
  SITE_SECRET: "str"
  custom_env_vars:
    - "match(^[A-Z_][A-Z0-9_]*=.+$)"
map:
  - config:rw
hassio_api: true
homeassistant_api: false
auth_api: false
hassio_role: "default"
