name: Build and test Traefik

env:
  ADD_ON_DIRECTORY: traefik

on:
  schedule:
    - cron: "0 4 * * 4"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run builder (Docker directly)
        run: |
          docker run --rm \
            --privileged \
            -v "${{ github.workspace }}:/data" \
            ghcr.io/home-assistant/amd64-builder:latest \
            --test \
            --target /data/${{ env.ADD_ON_DIRECTORY }} \
            --amd64 \
            --aarch64 \
            --docker-hub boomam \
            --image ${{ env.ADD_ON_DIRECTORY }}-add-on
